"""
Renders the LangGraph pipeline's actual node graph as a shareable diagram.

Unlike a hand-drawn n8n canvas screenshot, this is generated straight from
the compiled graph object, so it's always an accurate picture of what the
code actually does - proof the architecture is real, not just described.

Usage:
    python visualize_graph.py
    -> writes output/architecture.html (open in a browser, screenshot it)
    -> writes output/architecture.mmd  (raw Mermaid source, paste into
       mermaid.live or a README if you want it to render on GitHub)
"""

import os
from graph import build_graph

# Mermaid is vendored locally (vendor/mermaid.min.js) instead of loaded from
# a CDN, so the generated diagram opens instantly and works completely
# offline - no dependency on network access when you open/screenshot/share it.
VENDOR_MERMAID_PATH = os.path.join(os.path.dirname(__file__), "vendor", "mermaid.min.js")

HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Lead Finder - Agent Architecture</title>
<script>
{mermaid_js}
</script>
<style>
  :root {{
    color-scheme: light;
    --surface-1: #fcfcfb;
    --page: #f9f9f7;
    --text-primary: #0b0b0b;
    --text-secondary: #52514e;
    --muted: #898781;
    --border: rgba(11,11,11,0.10);
    --accent: #2a78d6;
  }}
  @media (prefers-color-scheme: dark) {{
    :root {{
      color-scheme: dark;
      --surface-1: #1a1a19;
      --page: #0d0d0d;
      --text-primary: #ffffff;
      --text-secondary: #c3c2b7;
      --muted: #898781;
      --border: rgba(255,255,255,0.10);
      --accent: #3987e5;
    }}
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0;
    background: var(--page);
    color: var(--text-primary);
    font-family: system-ui, -apple-system, "Segoe UI", sans-serif;
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: 40px 16px 64px;
  }}
  header {{
    text-align: center;
    max-width: 640px;
    margin-bottom: 28px;
  }}
  h1 {{
    font-size: 22px;
    font-weight: 650;
    margin: 0 0 8px;
  }}
  p {{
    color: var(--text-secondary);
    font-size: 14px;
    line-height: 1.5;
    margin: 0;
  }}
  .card {{
    background: var(--surface-1);
    border: 1px solid var(--border);
    border-radius: 16px;
    padding: 32px;
    max-width: 900px;
    display: inline-flex;
    justify-content: center;
  }}
  .mermaid {{
    width: 100%;
  }}
  footer {{
    margin-top: 20px;
    color: var(--muted);
    font-size: 12px;
  }}
</style>
</head>
<body>
  <header>
    <h1>Lead Finder — Multi-Agent Pipeline</h1>
    <p>Researcher -&gt; Personalizer -&gt; Critic, with a self-correcting revise
    loop. Rendered directly from the compiled LangGraph object.</p>
  </header>
  <div class="card">
    <pre class="mermaid">
{mermaid_source}
    </pre>
  </div>
  <footer>Generated by visualize_graph.py</footer>
  <script>
    mermaid.initialize({{
      startOnLoad: true,
      theme: window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'default',
    }});
  </script>
</body>
</html>
"""


def main():
    app = build_graph()
    mermaid_source = app.get_graph().draw_mermaid()

    if not os.path.exists(VENDOR_MERMAID_PATH):
        raise SystemExit(
            f"Missing {VENDOR_MERMAID_PATH}. This should be checked into the repo "
            "(vendor/mermaid.min.js) - if it's missing, run:\n"
            "  npm install mermaid@11 --no-save --prefix /tmp/mermaid_fetch\n"
            "  cp /tmp/mermaid_fetch/node_modules/mermaid/dist/mermaid.min.js vendor/"
        )
    with open(VENDOR_MERMAID_PATH, "r", encoding="utf-8") as f:
        mermaid_js = f.read()

    os.makedirs("output", exist_ok=True)

    mmd_path = "output/architecture.mmd"
    with open(mmd_path, "w", encoding="utf-8") as f:
        f.write(mermaid_source)

    html_path = "output/architecture.html"
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(HTML_TEMPLATE.format(mermaid_source=mermaid_source, mermaid_js=mermaid_js))

    print(f"Written {mmd_path}")
    print(f"Written {html_path}  (open this in a browser and screenshot it)")


if __name__ == "__main__":
    main()
